#!/bin/bash
# This tests the /signin endpoint 

# substitute into the curl command
curl -i -H "Content-Type: application/json" \
   -X GET -d '{"url": "https://www.youtube.com/"}' \
   -c cookie-jar -k http://cs3103.cs.unb.ca:8028/url
