#!/bin/bash
# This tests the /signin endpoint 

# Read url
read -r -p "url: " url

# substitute into the curl command
curl -i -H "Content-Type: application/json" \
   -X GET -d '{"username": "'$url'"}' \
   -c cookie-jar -k http://cs3103.cs.unb.ca:8028/url
