    
DELIMITER //
DROP PROCEDURE IF EXISTS InitializeDatabase //
CREATE PROCEDURE InitializeDatabase()
BEGIN
    CREATE TABLE IF NOT EXISTS USER (
        ID INT PRIMARY KEY AUTO_INCREMENT,
        UNAME VARCHAR(100) NOT NULL
    );

    CREATE TABLE IF NOT EXISTS URL (
        ID INT PRIMARY KEY AUTO_INCREMENT,
        LONGURL VARCHAR(256) NOT NULL,
        TINYURL VARCHAR(256) NOT NULL,
        USERID INT,
        FOREIGN KEY (USERID) REFERENCES USER(ID)
    );
END //

DELIMITER ;
